Force Python version on Travis
This fixes an error

    TypeError: Plain typing.NoReturn is not valid as type argument

The error is due to a bug in Python 2.7.1

https://bugs.python.org/issue34921